"""Add LearningProgress table

Revision ID: 095f73bb90c7
Revises: 8bac43727caf
Create Date: 2026-02-19 09:14:43.762466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095f73bb90c7'
down_revision = '8bac43727caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chapter_name', sa.String(length=100), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('is_learned', sa.Boolean(), nullable=True),
    sa.Column('games_completed', sa.Boolean(), nullable=True),
    sa.Column('quiz_completed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_progress')
    # ### end Alembic commands ###
