"""add password_hash

Revision ID: 24585e06935b
Revises: 7c8cbdfebd36
Create Date: 2026-02-05 20:59:33.476668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24585e06935b'
down_revision = '7c8cbdfebd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_streaks')
    op.drop_table('user_xp')
    with op.batch_alter_table('langchain_pg_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cmetadata_gin'), postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')

    op.drop_table('langchain_pg_embedding')
    op.drop_table('user_badges')
    op.drop_table('langchain_pg_collection')
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('standard', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_stars', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['student_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('total_xp')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_xp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('total_stars')
        batch_op.drop_column('total_score')
        batch_op.drop_column('standard')
        batch_op.drop_column('student_id')

    op.create_table('langchain_pg_collection',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='langchain_pg_collection_pkey'),
    sa.UniqueConstraint('name', name='langchain_pg_collection_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_badges',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('badge_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('earned_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True)
    )
    op.create_table('langchain_pg_embedding',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_pg_embedding_pkey'))
    )
    with op.batch_alter_table('langchain_pg_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cmetadata_gin'), ['cmetadata'], unique=False, postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')

    op.create_table('user_xp',
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('xp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_xp_pkey'))
    )
    op.create_table('user_streaks',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('streak_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('last_login', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_streaks_pkey'))
    )
    # ### end Alembic commands ###
