"""Add xp and level fields

Revision ID: 8bac43727caf
Revises: 24585e06935b
Create Date: 2026-02-19 09:01:36.079264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bac43727caf'
down_revision = '24585e06935b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_xp', sa.Integer(), nullable=True))

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('badges', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_column('badges')
        batch_op.drop_column('level')
        batch_op.drop_column('xp_points')

    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.drop_column('total_xp')

    # ### end Alembic commands ###
