"""Update TeacherQuiz to use users table

Revision ID: 2e6289bb8022
Revises: 58422d8ea7ae
Create Date: 2026-02-21 14:13:13.454412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6289bb8022'
down_revision = '58422d8ea7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teacher_quizzes_teacher_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teacher_quizzes_teacher_id_fkey'), 'teachers', ['teacher_id'], ['id'])

    # ### end Alembic commands ###
