"""add teacher_mode tables

Revision ID: 58422d8ea7ae
Revises: 064bb82011fa
Create Date: 2026-02-21 13:56:03.709173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58422d8ea7ae'
down_revision = '064bb82011fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teacher_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_class', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['teacher_quizzes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_code')
    )
    op.create_table('teacher_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=200), nullable=False),
    sa.Column('option_b', sa.String(length=200), nullable=False),
    sa.Column('option_c', sa.String(length=200), nullable=False),
    sa.Column('option_d', sa.String(length=200), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['teacher_quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['teacher_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['live_quiz_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_quiz_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['live_quiz_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_quiz_scores')
    op.drop_table('live_quiz_answers')
    op.drop_table('teacher_questions')
    op.drop_table('live_quiz_sessions')
    op.drop_table('teacher_quizzes')
    op.drop_table('teachers')
    # ### end Alembic commands ###
