"""comprehensive schema refactoring

Revision ID: c55aceb08d37
Revises: 041753d262a3
Create Date: 2026-02-20 22:19:32.264623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c55aceb08d37'
down_revision = '041753d262a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=100), nullable=False),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('expiry_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('expires_at')
        batch_op.drop_column('otp')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('feedback_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.drop_column('standard')

    with op.batch_alter_table('live_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_level_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('puzzle_data', sa.JSON(), nullable=False))
        batch_op.drop_constraint(batch_op.f('puzzle_topic_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'game_level', ['game_level_id'], ['id'])
        batch_op.drop_column('question')
        batch_op.drop_column('puzzle_type')
        batch_op.drop_column('image_url')
        batch_op.drop_column('topic_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_level_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('question_topic_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'game_level', ['game_level_id'], ['id'])
        batch_op.drop_column('topic_id')

    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_level_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time_taken', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('quiz_attempt_topic_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'game_level', ['game_level_id'], ['id'])
        batch_op.drop_column('topic_id')

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=200), nullable=True))
        batch_op.drop_constraint(batch_op.f('student_profile_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('standard')
        batch_op.drop_column('avatar_id')
        batch_op.drop_column('school_name')
        batch_op.drop_column('total_stars')

    with op.batch_alter_table('student_topic_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_accessed', sa.DateTime(), nullable=True))
        batch_op.drop_column('unlocked_at')
        batch_op.drop_column('is_completed')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('level_number', sa.Integer(), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('topic_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('animations_url', sa.JSON(), nullable=True))
        batch_op.drop_column('diagram_url')
        batch_op.drop_column('theory')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('theory', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('diagram_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('animations_url')
        batch_op.drop_column('images')
        batch_op.drop_column('lesson_text')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('level_number')
        batch_op.drop_column('topic_name')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('student_topic_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unlocked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_accessed')
        batch_op.drop_column('lesson_completed')

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_stars', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('school_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avatar_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('standard', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_profile_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('school')
        batch_op.drop_column('avatar')
        batch_op.drop_column('points')
        batch_op.drop_column('grade')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quiz_attempt_topic_id_fkey'), 'topic', ['topic_id'], ['id'])
        batch_op.drop_column('time_taken')
        batch_op.drop_column('game_level_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('question_topic_id_fkey'), 'topic', ['topic_id'], ['id'])
        batch_op.drop_column('game_level_id')

    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('puzzle_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('puzzle_topic_id_fkey'), 'topic', ['topic_id'], ['id'])
        batch_op.drop_column('puzzle_data')
        batch_op.drop_column('game_level_id')

    with op.batch_alter_table('live_quiz', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('rank')
        batch_op.drop_column('grade')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('feedback_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('student_id')

    with op.batch_alter_table('email_otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('expiry_time')
        batch_op.drop_column('otp_code')

    op.drop_table('game_level')
    # ### end Alembic commands ###
